### ISSUE TITLE
[XQuery] DirPIConstructor permits ':' in the PI name.

### ISSUE THREAD

**Issue by rhdunn** [qt4cg/qtspecs#89] opened 2021-09-02 18:58 UTC
## Overview
The `PITarget` symbol allows a colon in the grammar, but the rest of the spec and XQuery implementations (tested on BaseX, Saxon, and MarkLogic) disalow `:` in `DirPIConstructor` productions.

## Details
The `DirPIConstructor` construct is defined as:
```
[151] DirPIConstructor ::= "<?"  PITarget  (S DirPIContents)?  "?>" | /* ws: explicit */
[232] PITarget ::= [http://www.w3.org/TR/REC-xml#NT-PITarget]XML /* xgc: xml-version */
```
with XML defining `PITarget` as:
```
[17] PITarget ::= Name - (('X' \| 'x') ('M' \| 'm') ('L' \| 'l'))
```

The "excluding 'xml' in any case insensitive form" part is covered by the *3.9.2 Other Direct Constructors* section.

While the XML specification states:
> The Namespaces in XML Recommendation [XML Names] assigns a meaning to names containing colon characters. Therefore, authors should not use the colon in XML names except for namespace purposes, but XML processors must accept the colon as a name character.

various XQuery processors disallow a colon here in line with the rest of the XQuery specification.

## Proposal
Change `PITarget` to:
```
[232] PITarget ::= NCName
```
to reflect actual usage and align it with the rest of the XQuery specification.

**Comment by rhdunn** [comment] 2021-09-02 19:03
For consistency, `PITest` and `CompPIConstructor` should then be updated to use `PITarget` instead of `NCName`.

**Comment by michaelhkay** [comment] 2022-10-07 16:09
I note also that 3.6.3.1 says

> If the specified PITarget is not a syntactically valid NCName, a type error is raised [err:XPTY0004]

This is rather bizarre as the PITarget is statically known. If we change it as proposed here, this becomes a grammar violation

**Comment by michaelhkay** [comment] 2022-10-07 16:25
I attempted to make this change and couldn't get the grammar to build. My understanding of the grammar machinery is fairly limited. I'm happy for someone else to have a go; I don't think the problem is sufficiently critical to spend any more time on it.

**Comment by michaelhkay** [comment] 2022-10-07 16:35
I've left the grammar as is and added a phrase to the rules for direct processing instructions that says the PITarget must not contain a colon. I think that's enough to close the issue.

**Comment by michaelhkay** [comment] 2023-04-24 10:49
This has been fixed (by means of narrative text, rather than changing the grammar).

**Closed by michaelhkay** 2023-04-24 10:49 UTC
Labels: Bug, XQuery, Editorial
