### ISSUE TITLE
Almost all functions in FO that must process multiple string items, can have as a parameter only a single collation

### ISSUE THREAD

**Issue by dnovatchev** [qt4cg/qtspecs#1305] opened 2024-06-25 19:22 UTC
**The problem**:

At present the only XPath 4 function (that I am aware of) that can process multiple strings and use multiple collations (a specific collation for a specific string comparison) is [**`fn:sort`**](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#func-sort).

Some very important functions, such as [**`fn:deep-equal`**](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#func-deep-equal) and [**`fn:compare`**](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#func-compare) can have only one collation as a parameter.

This means that when we are comparing sequences of items which contain multiple strings each of which could need to be handled in a specific collation, we are not able to provide all such collations (but are providing just a single collation) to the comparing function - `fn:deep-equal` or `fn:compare`.

The end result is that all string comparisons will be done using that single collation and may not produce the correct result (that would be produced if the particular comparison was done with the particular collation).

**Possible solutions**.

It is difficult to provide a solution to this problem and the list below is open ended:

1. Add a **`collation`** property to the type `xs:string`. 
   Then we would specify the type as **`(xs:string, collation-name?)`**

2. Make `fn:deep-equal` and `fn:compare` accept not a single collation but a sequence of collation-names.
   In this case a pair of strings will be compared once for every collation that is specified. The idea is that the sequence of collations would be provided ordered by decreasing specificity. The first result that is produced at least twice in this process (something like voting) would be the result of the comparison. In case of a tie, the comparison done with the collation that is earliest (supposed to be more specific) will have higher priority.

3. Leave this as it is at present, but add to the specification a warning to the user that specifying a single collation-name may not be what they want.

4. Remove from `fn:sort` the multiple-collations parameter and allow only a single collation.

**Comment by ndw** [comment] 2024-06-26 06:56
My understanding of `fn:sort` is that it provides a list of collations only so that you can specify different collations for different sort keys: sort by last-name using the EN-GB collation, then sort by employee-id using the Unicode code-point collation. It doesn't consider more than one collation for any given comparison.

I can't quickly construct a scenario where I think "compare these two items with these three collations and consider them a match if they are the same with any one of those collations" is likely to be comprehensible behavior.

I think it's sufficient to provide one collation to go with any operation that requires one. If your needs are more sophisticated than that, and perhaps sometimes they are, you'll have to do the sophisticated work by hand. I think that's consistent with other design choices that we've made.

With respect to the options you outlined, I think option 1 would not only be a complete redesign of string handling across the whole family of specifications, we also have strong evidence that experts in internationalization would be opposed to it. I don't think option 2 is viable for the reasons I outlined above. And I think option 4 is based on a misunderstanding of how multiple collations are used in `fn:sort`.

I think the status quo is fine, and I don't think it's necessary to add any warnings. If there is a consensus to add a warning, I hope that we can craft one carefully so that it doesn't *cause* more confusion than clarification. If I have some sophisticated use case where I think I need to consider multiple collations and I have a function that only accepts a single collation, I think my natural reaction is going to be "huh, I guess I have to do a little more work here" not ... something else

**Comment by michaelhkay** [comment] 2024-06-26 08:50
It would be useful if you could supply (a) some use cases where this is needed, and (b) some examples of how specific functions (say index-of) would work.

**Comment by rhdunn** [comment] 2024-06-26 11:07
Collations define the ordering of characters/codepoints when performing string comparisons for sorting. They apply to the set of strings in the same group (e.g. family names) and context (e.g. head words in a dictionary). As such, it doesn't make sense to associate a string with a collation.

Microsoft's "Collation, sorting, and string comparison" page [1] has various examples of different collations and their use cases, including:
> Sorting can even change within one language depending on the context. For example, in Germany phonebook ordering is different than dictionary ordering.

So here you have a case where the same string can have a different collation. Likewise for strings that consist of Chinese, Japanese, or Korean characters.

You may also have cases where you want a case-sensitive ordering/matching and others a case-sensitive ordering/matching. Those apply to the context, not to the specific strings.

As has been noted, `fn:sort` is designed to allow different collations on different contexts (sort keys) not strings.

[1] https://learn.microsoft.com/en-us/globalization/locale/sorting-and-string-comparison

**Comment by dnovatchev** [comment] 2024-06-26 18:09
> It would be useful if you could supply (a) some use cases where this is needed, and (b) some examples of how specific functions (say index-of) would work.


Here is a sketch  how to construct an example if one knows the exact collations to use (I don't):

 `$seq1` contains two strings - one is a German word that has two different spellings - like **_Gruen_** and **_Grün_**, and the second string is one with similar properties (has two different spellings) but in another language (say French or Spanish, or ...)

 `$seq2` contains the same two strings as $seq1 but with their different spellings, that are considered `equal` under the respective collation - German and (say French or Spanish, or ...).
 
 We want to perform `deep-equal($seq1, $seq2)` and want the result to be `true()`.
 
 We can specify a `$collation1` under which the first strings will be equal - but the second strings will not be equal.
 
 Alternatively, we can specify a `$collation2` under which the second strings will be equal - but the first strings will not be equal.
 
 If we could specify two collations instead of one, then the first strings will be equal using `$collation1` and the second strings will be equal using `$collation2`.
 
 Thus, regardless of which collation we provide as parameter to `deep-equal`, the result of the comparison will be `false()`, but we want it to be `true()`.
 
 As someone wanted to search for key-names of a map using a collation, this would only be usable if all key-names are comparable under the same collation.  
 
 Imagine the names of scientists in an international organization, for a practical example. We may have problems using their names as keys of a map and wanting to be able to specify either of any possible name-spelling.

**Comment by rhdunn** [comment] 2024-06-26 18:49
1. How do you identify whether a string contains German, French, etc. when extracting it from e.g. a text node?
2. How do you deal with cases where a text string contains mixed words (e.g. in a book title, wikipedia/TEI/JATS/etc. article about a person, or thing in a different language, an article/book/etc. with authors from different countries (esp. if they have married someone from another country and have e.g. a Spanish given name and a Finnish family name), etc.) [1]?
3. How does comparison/sorting work when the collations are different as there is then no stable order to the characters/codepoints -- see e.g. [2]: "Finnish ⟨w⟩ is generally regarded as equivalent to ⟨v⟩ (in a multilingual context it may, however, be collated separately after ⟨v⟩, as in English)."?
4. How do you sort the head words in e.g. an English dictionary where some of those words are foreign in origin (e.g. zeitgeist, schadenfreude, hygge, etc.) but have entered common usage?

[1] Works like those of Edgar Allan Poe contain a mix of words, phrases, etc. in different languages like Greek, French, Italian, German as well as being predominantly in English. It is also common for news articles to reference place names, people, and other words in the language of the country they are talking about -- especially in wars, earthquakes, volcanoes (like the ones in Iceland), etc.

[2] https://en.wikipedia.org/wiki/Finnish_orthography#Collation_order

**Comment by rhdunn** [comment] 2024-06-26 19:04
Another issue with this is that it will make integrating with or using databases as a backend impossible. See e.g. [1]. Databases generally:
1. allow you to specify a single collation to a column;
2. allow you to optionally specify a collation on an index to e.g. allow different sorting semantics, although this is not supported by all databases;
3. allow you to specify a collation when sorting on a given column;
4. require you to specify the collation when joining columns with different collations.

Here, fn:sort is like sorting on different columns (sort keys) and providing a collation for each of those. It is not providing multiple collations for the same column (sort key, etc.).

[1] https://www.red-gate.com/simple-talk/databases/sql-server/t-sql-programming-sql-server/questions-sql-server-collations-shy-ask/

**Comment by dnovatchev** [comment] 2024-06-26 19:12
> 1. How do you identify whether a string contains German, French, etc. when extracting it from e.g. a text node?
> 
>     2. How do you deal with cases where a text string contains mixed words (e.g. in a book title, wikipedia/TEI/JATS/etc. article about a person, or thing in a different language, an article/book/etc. with authors from different countries (esp. if they have married someone from another country and have e.g. a Spanish given name and a Finnish family name), etc.) [1]?
> 
>     3. How does comparison/sorting work when the collations are different as there is then no stable order to the characters/codepoints -- see e.g. [2]: "Finnish ⟨w⟩ is generally regarded as equivalent to ⟨v⟩ (in a multilingual context it may, however, be collated separately after ⟨v⟩, as in English)."?
> 
>     4. How do you sort the head words in e.g. an English dictionary where some of those words are foreign in origin (e.g. zeitgeist, schadenfreude, hygge, etc.) but have entered common usage?
> 
> 
> [1] Works like those of Edgar Allan Poe contain a mix of words, phrases, etc. in different languages like Greek, French, Italian, German as well as being predominantly in English. It is also common for news articles to reference place names, people, and other words in the language of the country they are talking about -- especially in wars, earthquakes, volcanoes (like the ones in Iceland), etc.
> 
> [2] https://en.wikipedia.org/wiki/Finnish_orthography#Collation_order

Yes Reece,

All the comments above are just a good argument why comparing strings using a single collation may not in general produce the expected result.

So either we do not specify a collation at all, or provide a set of collations and a rule, maybe such as: "_Two strings are equal if there is at least one collation of the specified, under which they are equal._"

**Comment by dnovatchev** [comment] 2024-06-26 19:17
> Another issue with this is that it will make integrating with or using databases as a backend impossible. See e.g. [1]. 

Yes.

And we are not talking about databases here - just about (internal, during single execution)  `deep-equal()` results.

In a related thread @michaelhkay was considering even using `collation-key` as the key-name and this is also not persistable outside of the lifetime of a single execution, because different implementations (and even different versions of the same implementation)  produce different collation-keys for the same string

**Comment by dnovatchev** [comment] 2024-06-26 19:35
> With respect to the options you outlined, I think option 1 would not only be a complete redesign of string handling across the whole family of specifications, we also have strong evidence that experts in internationalization would be opposed to it.

As far as I understood the statement of @cmsmcq the experts are against the idea for a string to have a **collation**-property

What is proposed in option 1 is not tho give a specific string a  collation as permanent property, but to be able to **_attach a collation to a specific string_** just for the lifetime/scope of a particular (sub)expression.

This means that the same string can have different collations attached to it in different sub-expressions. Could be quite useful.

Of course, saying that "Gruen" has a permanent collation property of "SomeGermanCollation" would be very restricting and wrong in general, and this is not what option1 is about.

**Comment by michaelhkay** [comment] 2024-06-26 20:11
>So either we do not specify a collation at all, or provide a set of collations and a rule, maybe such as: "Two strings are equal if there is at least one collation of the specified, under which they are equal."

In general that will give you a non-transitive equality operation, which will break many functions such as distinct-values(). With sorting, a collation that doesn't implement a total ordering is very likely to cause non-termination. This is territory where angels should fear to tread.

**Comment by dnovatchev** [comment] 2024-06-26 20:37
> > So either we do not specify a collation at all, or provide a set of collations and a rule, maybe such as: "Two strings are equal if there is at least one collation of the specified, under which they are equal."
> 
> In general that will give you a non-transitive equality operation, which will break many functions such as distinct-values(). With sorting, a collation that doesn't implement a total ordering is very likely to cause non-termination. This is territory where angels should fear to tread.

OK, so **_we do recognize the problem_**, and we have not yet found a good solution.  
Even this is a good step forward.

I think if we could have a **union of collations**, then equality would be transitive.

**Comment by dnovatchev** [comment] 2024-06-28 15:18
> In general that will give you a non-transitive equality operation, which will break many functions such as distinct-values().

Actually, an equality comparison operation using the same union of collations is transitive.

We define it as: 

**_Two strings are equal if there is at least one collation in the specified set of collations, using which the two strings are equal._**

**Comment by michaelhkay** [comment] 2024-06-28 16:00
Sure. If Gruen and Grün are equal under German collation, while Gruen and Grven are equal under MedievalLatin collation, it may well be the case that there is no collation under which Grün and Grven are equal.

**Comment by dnovatchev** [comment] 2024-06-28 16:31
> Sure. If Gruen and Grün are equal under German collation, while Gruen and Grven are equal under MedievalLatin collation, it may well be the case that there is no collation under which Grün and Grven are equal.

Great.

This proves that the so defined string equality is not transitive.

**How about we define string equality as**:

"Two strings s1 and s2 are equal when compared with a set of collations `COL = {c1, c2, ..., cn}` if there exists a sequence of strings:
 `(sm1, sm2, ... smk)`, and a sequence of collations from COL such that :
 
 `equal(s1, sm1, cm1) and equal(sm1, sm2, cm1) and ... equal(cmk, s2, cmk)`
 
 This is essentially the problem of "word ladders", which has a good and efficient graph-search based solution, and which I had the pleasure of implementing in the past in pure XSLT : "[Word Ladders, or How to go from “angry” to “happy” in 20 steps](https://dnovatchev.wordpress.com/2012/11/26/word-ladders-or-how-to-go-from-angry-to-happy-in-20-steps/)"
"

With this definition we will have :

`equal("Grün", "Gruen",  "German")  and equal("Gruen", "Grven", "Medieval") `

thus, this means:

`equal("Grün", "Grven", COL)`

**Comment by rhdunn** [comment] 2024-06-28 17:05
The equality and transitivity is given by the collation. With a single collation there is a well-defined ordering and comparison of codepoints.

The issue is when dealing with multiple collations where the ordering differs -- such as a diacritic insensitive collation that orders diacritic versions of letters along side the same letter (ignoring the diacritic) and e.g. a finnish collation that defines where the finish diacritic letter A variants are placed. I.e. you have a diagreement on the placement of the diacritic A variants so don't know how to select which collation takes precence. And if you did you would break the collations, e.g. if an author said "I want this table to be in finnish collation ordering" e.g. by specifying a default or explicit collation.

Lets say that F is a finnish collation and DI is a diacritic insensitive collation. If strings A and B are in F and C and D are in DI then how do you order those strings? With multiple collations you could get different answers comparing (A, C), (A, B), (B, C), etc. such that no unique ordering can be found.

**Comment by dnovatchev** [comment] 2024-06-28 17:10
> The issue is when dealing with multiple collations where the ordering differs

We are not talking about ordering here (yet) - just about equality.

I provided a definition of equality that is transitive over a **set** of collations.

**Comment by rhdunn** [comment] 2024-06-28 18:26
Collations are used for sorting as well as equality, as per fn:sort, etc.

**Comment by dnovatchev** [comment] 2024-06-28 19:37
> Collations are used for sorting as well as equality, as per fn:sort, etc.

Yes. Here we are discussing **equality** with collations, and a probable improvement of functions as `deep-equal`, ` index-of, ..., ` etc.

**Comment by rhdunn** [comment] 2024-06-28 19:51
But whatever approach we choose for equality needs to work with sorting/ordering. That's because collations are used for both of these and thus needs to work for both.

An implementation may use things like an index to provide the functionality.

**Comment by dnovatchev** [comment] 2024-06-28 20:23
> But whatever approach we choose for equality needs to work with sorting/ordering. That's because collations are used for both of these and thus needs to work for both.
> 
> An implementation may use things like an index to provide the functionality.

Yes, but we may use **different** approaches for equality and for sorting.

**Comment by dnovatchev** [comment] 2024-06-28 20:35
> > But whatever approach we choose for equality needs to work with sorting/ordering. That's because collations are used for both of these and thus needs to work for both.
> > An implementation may use things like an index to provide the functionality.
> 
> Yes, but we may use **different** approaches for equality and for sorting.

Actually, we don't have any problems with sorting at all.

**Comment by michaelhkay** [comment] 2024-10-04 15:34
I don't think this discussion led to any concrete proposals for changes to the language or function library, and I suggest that it is time to close it with no action.

**Comment by dnovatchev** [comment] 2024-10-04 16:43
> I don't think this discussion led to any concrete proposals for changes to the language or function library, and I suggest that it is time to close it with no action.

We may close it, but what is really important is that **this discussion did in fact produce a specific solution to the problem**. In this solution string equality is defined as the transient closure of strings-equality using a set of collations. The concrete example is in this comment: https://github.com/qt4cg/qtspecs/issues/1305#issuecomment-2197277953

Whether or not we modify the functions to accept a sequence of collations - this depends on our good will.

**Comment by dnovatchev** [comment] 2024-10-07 23:57
OK,

The proposal is to change the signatures of all functions in which there could be comparison of more than one pair of strings.

The current argument type of **_collation as xs:string?_** needs to be changed to **_collations as xs:string\*_**.

**Comment by michaelhkay** [comment] 2024-10-08 08:09
And the semantics?

**Comment by dnovatchev** [comment] 2024-10-08 20:04
I am trying to find the value of the right $collation argument, using which the following will evaluate to **0**:

`compare("Grün", "Gruen", $collation)`



@michaelhkay  (or anyone who knows), could you, please, help?

Using `'http://www.w3.org/2013/collation/UCA?lang=de;strength=primary'` produces **1**, not **0**.

**Comment by ChristianGruen** [comment] 2024-10-08 21:12
> @michaelhkay (or anyone who knows), could you, please, help?

I can’t (possibly because I’m neither Mike nor a collation expert), but one reason why collations don’t allow you to equate `u` and `ü` could be that there are many German words in which `ue` cannot be replaced with `ü`. An arbitrary example is `Bauerde`, which contains `Bau` (construction) and `Erde` (soil), whereas `Baürde` does not exist.

The following query returns `0`:

```xquery
compare('ü', 'u', 'http://www.w3.org/2013/collation/UCA?lang=de;strength=primary')
```

**Comment by michaelhkay** [comment] 2024-10-08 21:34
I don't know any way to achieve this in UCA. As Christian says, while `ü` is often expanded to `ue` in contexts where diacritics are not available, the two strings are not really equal.

**Comment by michaelhkay** [comment] 2024-10-08 21:45
Incidentally, if there really is a requirement for an equality comparison of the form "consider two strings as equal under (C1, C2, C3) if they are equal under C1 or equal under C2 or equal under C3", then I would handle that by defining a collation URI to represent this comparison rule; the collation URI might be formed as a composite URI containing C1, C2, and C3 as query parameters. However, for deep-equal() I would think it's usually more practical to define an items-equal callback function.

I'm not at all convinced this issue is addressing a genuine requirement. While I've seen a wide variety of requirements for equality matching that goes beyond what we offer with UCA collations, I think the requirements nearly always involve some kind of "semantic equality", for example "CA"="Canada" (or "CA"="California") or "Ave"="Avenue", and I think that stretching the collation concept to handle such things is the wrong approach.

**Comment by ndw** [comment] 2024-10-09 09:03
Unless I'm mistaken, the proposed semantics for a deep-equal or compare function that took a sequence of collations would be that two arbitrary strings would be considered equal if they were equal according to any of the provided collations. If that's correct, I am not at all persuaded that those are generally useful semantics.

If I have a couple of nodes that have, for example, author names in them and those names are in several languages, 

1. If I compare two German names, I want to use the German collation
2. If I compare a German name and a French name, I want them to be unequal
3. If I compare two Urdu names, I want to use the Urdu collation
4. If the German name and the French name happen to be equal according to the Urdu collation, it would be an error to report that they're equal (I mean, an error from my perspective, if they're equal under the Urdu collation, then they're equal, under that collation).

I don't think there's a problem here that can be solved by passing in a list of collations. If you have strings in different languages and the languages in question aren't identified by `xml:lang` attributes or some other mechanism, I think you're out of luck. If they are identified, then you want to use the correct collation for the languages identified, not a union of all the collations provided.

**Comment by ChristianGruen** [comment] 2024-10-09 09:12
> Unless I'm mistaken, the proposed semantics for a deep-equal or compare function that took a sequence of collations would be that two arbitrary strings would be considered equal if they were equal according to any of the provided collations.

An existing syntax for that would be:

```xquery
some(($coll1, $coll2), deep-equal($string1, $string2, ?))
```

`fn:every` could be used if all collations must match.

**Comment by michaelhkay** [comment] 2024-10-09 09:32
>If I compare a German name and a French name, I want them to be unequal

And even though you've shown that the problem is complex, real life is far more complex. There are of course no such categories as "German names" and "French names". What language code would you attach to "van der Vlist"? I have a Norwegian friend with the surname Palmström, which is a Swedish name, so in Norwegian he often spells it Palmstrøm. These problems have to be tackled at the application level, there's no way we can do them justice at the programming language level.

**Comment by ChristianGruen** [comment] 2024-10-09 10:03
> And even though you've shown that the problem is complex, real life is far more complex.

True. It’s one of the reasons why [XQuery Full Text](https://www.w3.org/TR/xpath-full-text-10/) comes with its own complex tokenization machinery that more or less ignores collations (and it still lacks many features that are required in practice).

**Comment by ndw** [comment] 2024-10-09 10:24
Indeed. Famously, [falsehoods programmer's believe about names](https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/). I wasn't attempting to enumerate *all* the ways that it was complex, just that it was more complex than we could handle with a list of collations! 😄

**Comment by rhdunn** [comment] 2024-10-09 10:48
Looking at the problem statement (comparing documents with mixed languages) I wonder if it makes sense to have some sort of language-aware comparison. I.e.:
1. pass a collation map of language codes (BCP-47) to collation;
2. have a mechanism to select a collation for a given node (e.g. locating a html:lang/xml:lang attribute and using the BCP-47 language matching logic to find the best matching collation in the map);
3. be able to specify a fallback collation to use when either no matching collation exists or the selected collations are different.

Regarding the proposed approach -- Are there any other programming languages that support multi-collation comparisons like this? IIUC, SQL, Java, C#, etc. only support using a single collation for each column/comparison. If you need to support multiple natural languages/locales then you typically select a Unicode collation, e.g. by assigning that to a database column or creating the correct locale/culture instance.

**Comment by dnovatchev** [comment] 2024-10-09 15:42
> Unless I'm mistaken, the proposed semantics for a deep-equal or compare function that took a sequence of collations would be that two arbitrary strings would be considered equal if they were equal according to any of the provided collations. If that's correct, I am not at all persuaded that those are generally useful semantics.

Yes, that is the proposed solution.

This can tell us that the two sequences of strings are equal, even though any comparison with only a single collation returns **_false()_**.

I think that providing a sequence of collations when comparing two sequences of strings is thus better than being able only to specify a single collation.

If we decide that providing the collations is not useful, then we confirm that providing a (even a single) collation is also not useful to solve this problem. If so, then we should not support providing a collation at all for functions that compare **sequences** of strings. In addition, we need to put some text acknowledging this unsolved problem.

Even if providing a sequence of collations might not solve all cases, I believe that in many cases  this is better than providing only a single collation and getting a false **_false()_** result.

As @ndw points out, the proposed solution could return a false-positive in some cases, but we need to have (construct) at least one specific example in which this happens. If it turns out that it is very difficult to construct such an example, then the probability of getting false-positives might be close to negligible.

Yes, a difficult problem to crack - but at least this opens our eyes to be aware that just providing a single collation is not the universal solution to comparing **_sequences/sets_** of strings.

**Comment by ndw** [comment] 2024-10-09 15:58
I think where I come down is: the general problem is hugely complex and there probably isn't a general solution that works for a plurality of cases. The solution has to be tailored to suit the specific use cases. My intuition and experience suggest that most users are working with a single language most of the time, but of course with different single languages. Providing a single collation covers that case. Covering the use cases where multiple collations are needed requires a domain specific approach.  The extra complexity (and I bet, confusion) that is involved in supporting a sequence of collations doesn't seem justified. (To me. At this time.)

**Comment by dnovatchev** [comment] 2024-10-09 16:06
> I think where I come down is: the general problem is hugely complex and there probably isn't a general solution that works for a plurality of cases. The solution has to be tailored to suit the specific use cases. My intuition and experience suggest that most users are working with a single language most of the time, but of course with different single languages. Providing a single collation covers that case. Covering the use cases where multiple collations are needed requires a domain specific approach. The extra complexity (and I bet, confusion) that is involved in supporting a sequence of collations doesn't seem justified. (To me. At this time.)

Shouldn't we at least put text acknowledging that at present there doesn't exist a function in F&O that solves the general problem of comparing two sequences of strings?

I think that the best place for this note would be on **_fn:deep-equal_**, please correct me if you have a better place in mind.

**Comment by michaelhkay** [comment] 2024-10-09 16:17
>but at least this opens our eyes to be aware that just providing a single collation is not the universal solution to comparing sequences/sets of strings

Firstly, any algorithm for comparing strings can be regarded as a collation and can be assigned a URI.

Secondly, the deep-equal() function now allows strings to be compared using a user-defined function as an alternative to using a collation URI.

**Comment by ChristianGruen** [comment] 2024-10-09 16:25
> Yes, that is the proposed solution.

@dnovatchev So what would be returned by the following query?

```xquery
compare('a', 'B', (
  'http://www.w3.org/2005/xpath-functions/collation/html-ascii-case-insensitive',
  'http://www.w3.org/2005/xpath-functions/collation/codepoint'
))
```

I still don’t understand what problem you are trying to solve. Could you please give us a simple and relatable example?

**Comment by ndw** [comment] 2024-10-09 16:29
I don't personally think any such note is necessary or useful. I think it's clear what the current functions do and I think it's clear that they don't support multiple collations. If I know I need multiple collations, I know I'll have to consider carefully *how* I want to use them for my *specific application* and implement accordingly. 

A note of the form:

> Note: these functions don't natively support the use case of comparing strings with a set of collations

Wouldn't help me. I'd be puzzled why I was being told something that was self-evident from the description of the functions and I'd worry that I was fundamentally misunderstanding something. We don't have a note that says we don't have a function that solves the halting problem or a note that says we don't have functions that perform arithmetic with base 3 numbers, either.

What's more, I think @ChristianGruen showed a couple of examples of function composition that would solve the "compare a set of strings with a sequence of collations" problem. I just don't think that functionality all by itself goes very far in solving anyone's domain specific, undoubtedly complex use case where multiple collations are a requirement.

I'm not generally opposed to adding notes where they help clarify the spec. But we can't add notes for *every possible* clarification that could be made. That's not what language implementation specifications are for. And I think it's important to minimize the possibility that the note *itself* could confuse the reader.

**Comment by michaelhkay** [comment] 2024-10-09 17:35
>But we can't add notes for every possible clarification that could be made.

My father used to edit a handbook for students that was republished every year, and I remember a self-imposed rule he made: for every paragraph you add, you must find another one to take out. It's a great mistake to think that by adding to the information that we put into the spec, we are adding to the information that readers get out of it.

**Comment by ChristianGruen** [comment] 2024-10-09 17:50
> for every paragraph you add, you must find another one to take out.

A great rule. It reminds me of Blaise Pascal’s excuse in a letter – je n’ai fait celle-ci plus longue que parce que je n’ai pas eu le loisir de la faire plus courte.

**Comment by dnovatchev** [comment] 2024-10-10 15:22
> > but at least this opens our eyes to be aware that just providing a single collation is not the universal solution to comparing sequences/sets of strings
> 
> Firstly, any algorithm for comparing strings can be regarded as a collation and can be assigned a URI.
> 
> Secondly, the deep-equal() function now allows strings to be compared using a user-defined function as an alternative to using a collation URI.

Thanks @michaelhkay, 

I am not sure how difficult it will be to "assign an URI to any algorithm for comparing strings" and can this be done dynamically (evaluating an expression)?

Isn't it a more straight-forward solution to allow a user-written comparison function as an argument of deep-equal?

With the addition of this argument we have a solution to the current problem or any other type of such problems and then this issue would be resolved.

**Comment by ChristianGruen** [comment] 2024-10-10 16:21
> The simplest such example can be when there are two sequences […]

@dnovatchev Thanks for the example.

I would still be interested in your expected result for `compare('a', 'B', ...)`. It returns `1` and `-1` for collations that I mentioned, and I cannot see which results would be reasonable and intuitive for this function if multiple collations are specified (it frequently happens that results with different collations are contradictory).

> Someone with appropriate linguistic skills (knowledge of at least 2 languages) could probably give us such specific examples.

True, feedback from linguists would be very helpful. My experience is that standard XPath won’t make you happy anyway when you do serious text retrieval, whereas XQFT allows you to use all kind of language-specific tokenizers, stemmers, Thesaurus, etc.

**Comment by michaelhkay** [comment] 2024-10-10 16:31
>Isn't it a more straight-forward solution to allow a user-written comparison function as an argument of deep-equal?

Yes, which is why we did exactly that.

**Comment by dnovatchev** [comment] 2024-10-10 17:05
> > Isn't it a more straight-forward solution to allow a user-written comparison function as an argument of deep-equal?
> 
> Yes, which is why we did exactly that.
> 
> (Saxon has the capability to bind a URI to a collation algorithm written e.g. in Java, and such an algorithm can do more than just equality matching, it can also generate collation keys etc. This has benefits over using a user-written comparison function because it lends itself better to hashing, for example when doing unordered comparison of items in a sequence it means you can achieve O(n log n) performance rather than O(n^2).)

In the current F&O specification **[fn:deep-equal](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#func-deep-equal)** has this signature:

```xq
fn:deep-equal(
$input1 | as item()*, |  
$input2 | as item()*, |  
$options | as (xs:string \| map(*))? | := {'collation':fn:default-collation()}
) as xs:boolean
```

Calling this function one can provide the `$options` argument as a `map {'collation' : call-to-some-function-returning-a-collation-name, ...}`

Why can't we define the signature in a more straight-forward way, so that any `function(xs:string, xs:string) as xs:boolean` can be provided - say as value of a key, named "comparison-function' ?

I as a user feel this to be exactly what is necessary for solving any problematic case, without needing to write external functions.

**Comment by michaelhkay** [comment] 2024-10-10 17:27
You appear to have overlooked the items-equal() option.


items-equal | A user-supplied function to test whether two items are considered equal. The function can return true or false to indicate that two items are or are not equal, overriding the normal rules that would apply to those items; or it can return an empty sequence, to indicate that the normal rules should be followed. Note that returning () is not equivalent to returning false.Type: fn(item(), item()) as xs:boolean?Default: fn:void#0
-- | --


items-equal

A user-supplied function to test whether two items are considered equal. The function can return true or false to indicate that two items are or are not equal, overriding the normal rules that would apply to those items; or it can return an empty sequence, to indicate that the normal rules should be followed. Note that returning () is not equivalent to returning false.
Type: fn(item(), item()) as xs:boolean?
Default: [fn:void#0](file:///Users/mike/GitHub/mhk/qtspecs/build/www/xpath-functions-40/Overview.html#func-void)

**Comment by dnovatchev** [comment] 2024-10-10 18:03
> You appear to have overlooked the items-equal() option.
> items-equal 	A user-supplied function to test whether two items are considered equal. The function can return true or false to indicate that two items are or are not equal, overriding the normal rules that would apply to those items; or it can return an empty sequence, to indicate that the normal rules should be followed. Note that returning () is not equivalent to returning false.Type: fn(item(), item()) as xs:boolean?Default: fn:void#0

This is great.

I only wish that this would be more easily visible - one is lost in the long list of options.

Also, it needs to specify what would happen if both "collation" and "items-equal" are specified - for example, which of the two should be used - or maybe both one after the other?

Also, the name "items-equal" is not telling us that this actually must be a **function** that does the comparison. The meaning would be more obvious if the name was something like "comparison-function" or "item-comparer".

Or maybe even add a special argument:
 **`$item-comparer as function(xs:string, xs:string) as xs:boolean?`**

I hope that this feedback could be reflected to further improve the document.

With this clarification from @michaelhkay (thanks Mike!)  I think that we can close the issue, because there is actually (but quite well hidden...) solution already in the spec.

Thanks again to all who provided their input on this.

**Comment by ndw** [comment] 2024-10-15 16:05
The CG agreed to close this issue without further action at [meeting 094](https://qt4cg.org//meeting/minutes/2024/10-15.html).

**Closed by ndw** 2024-10-15 16:05 UTC
Labels: Bug, Enhancement, Discussion, Propose Closing with No Action
