### ISSUE TITLE
[FO] fn:intersperse

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qtspecs#2] opened 2020-11-30 16:47 UTC
A simple proposal, for a change:

A new function would be handsome to insert separators in a sequence. Equivalent functions exist in other languages; in Haskell and Dart, they are called `intersperse`:

### Summary

Inserts the defined separator between the items of a sequence and returns the resulting sequence.

### Signature

```xquery
fn:intersperse($values as item()*, $separator as item()*) as item()*
```

### Example

```xquery
let $div :=
  <div>
    <span>one</span>
    <span>two</span>
    <span>three</span>
  </div>
return fn:intersperse($div/span, ',')
```

**Comment by benibela** [comment] 2020-12-10 09:40
>`fn:intersperse($div/span, ',')`

Is that really better than ` tail($div/span!(',', .))  ` ?

**Comment by ChristianGruen** [comment] 2020-12-10 10:02
In the past, our users were asking for a function that works similar to `fn:string-join`, but can be applied to sequences. Similar to other sequence functions (including `fn:head`, `fn:tail`, `fn:subsequence`, `fn:remove`, and others that can be realized with filter expressions), the new function could make common tasks more convenient and accessible by a single function (i.e., a function in which you have to supply the input sequence only once).

An equivalent expression for the proposed function would be:

```xquery
head($sequence), tail($sequence) ! ($separator, .)
```

**Comment by michaelhkay** [comment] 2020-12-17 00:04
The `separator` attribute on `xsl:value-of` has certainly been a great invention, and I've proposed adding a `separator` attribute to `xsl:for-each`, so the use case certainly exists. 

So I agree this function would be useful.

**Comment by ChristianGruen** [comment] 2021-09-17 18:04
Alternative names: `fn:item-join`, `fn:sequence-join`.
What are your favorites?

**Comment by michaelhkay** [comment] 2021-09-17 19:18
I like "intersperse". "Join" is wrong, nothing is being joined. "Inject" would also work.

**Comment by joewiz** [comment] 2021-09-17 20:20
+1 to "intersperse" - as it suggests that something is being inserted *between* the items. Possibly, "interpose" or "delimit"?

**Comment by ChristianGruen** [comment] 2022-09-27 17:06
In the meeting, we discussed an inverse function for `fn:intersperse`. Maybe https://qt4cg.org/specifications/xpath-functions-40/Overview-diff.html#func-array-partition already fills the gap?

**Comment by michaelhkay** [comment] 2022-09-27 21:08
I found the discussion rather confusing. 

If the separators are single items, the problem is trivial, just remove all the items at even-numbered positions.

Otherwise, the problem is only soluble if the separator sequence can be distinguished from the other items; you're then looking to remove all subsequences that "match" some supplied sequence. Which I guess gets us back to functions for comparing sequences (for which one approach might be a generalised deep-equal).

But could someone tell me the use case?

**Comment by michaelhkay** [comment] 2022-09-30 16:20
The change has been accepted and implemented. Therefore closing the issue.

**Closed by michaelhkay** 2022-09-30 16:20 UTC
Labels: XQFO, Feature
