### ISSUE TITLE
Could the labeling of grammar productions be improved?

### ISSUE THREAD

**Issue by ndw** [qt4cg/qtspecs#1269] opened 2024-06-11 16:05 UTC
There was some discussion at [meeting 081](https://qt4cg.org/meeting/minutes/2024/06-11.html) about whether the labeling of grammar productions could be improved. The current numbering isn't stable, but may have useful implications. The productions appear in snippets, sometimes more than once in different places.

Could we do better? How?

**Comment by michaelhkay** [comment] 2024-06-11 19:05
The main difficulty with the numbering is that it makes diffs unusable when the numbering of productions changes.

Possible approaches include:

- Drop the production numbers entirely
- Use a stable numbering in which numbers are allocated in the grammar file and survive additions and deletions
- Find some way to get the diff tool to ignore differences in the numbers
- Use a numbering algorithm in which most rules are likely to retain their numbers when individual rules are added or deleted, e.g. use [C25] for the 25th rule beginning with the letter C.

**Comment by michaelhkay** [comment] 2024-06-16 18:03
The logic for allocating numbers appears to be in `grammar2spec.xsl` template `make-absolute-nt-number` at line 744.

I think the simplest solution is simply to adopt a convention of putting new production rules at the end of the grammar file; perhaps with a comment suggesting where it should be moved when we decide it's time to consolidate.

**Comment by michaelhkay** [comment] 2024-09-12 11:26
Closed as a duplicate of issue #1396

**Closed by michaelhkay** 2024-09-12 11:26 UTC
Labels: Editorial, Build
