### ISSUE TITLE
Namespace handling in parse-html

### ISSUE THREAD

**Issue by rhdunn** [qt4cg/qtspecs#379] opened 2023-02-28 12:09 UTC
The HTML5/"Living Standard" specification has two modes when it comes to handling namespaces:
1. For XHTML content the document is parsed as XML with full namespace support.
2. For HTML content, it has pseudo-namespace support.

For example, the HTML parsing algorithm:
1. places html, svg, and mathml elements in their corresponding namespaces.
2. allows certain element/attribute tag names (e.g. `xlink:href`) to be parsed as QNames.

From the XSLT/XQuery perspective, this affects the data model. Specifically, how to model and specify the node-names and the set of namespaces associated with a given element node.

**Comment by michaelhkay** [comment] 2023-02-28 12:42
The HTML5 standard includes (in §2.1.11) a "wilful violation" of the XPath 1.0 specification, specifically:

```
If the QName has no prefix and the principal node type of the axis is element, then the default element namespace is used. Otherwise if the QName has no prefix, the namespace URI is null. The default element namespace is a member of the context for the XPath expression. The value of the default element namespace when executing an XPath expression through the DOM3 XPath API is determined in the following way:

If the context node is from an HTML DOM, the default element namespace is "http://www.w3.org/1999/xhtml".
Otherwise, the default element namespace URI is null.
```

Reproducing this rule would indeed require a data model change: we would need to distinguish nodes that are "from an HTML DOM" from other nodes. This would also require any expression or instruction that creates a node to specify whether this property should be set on the node (a problem that didn't exist with XPath 1.0, which never creates new nodes).

There is another problem with the rule, which is that it's very ambiguous as to what it means by "the context node". Is this the context node for the XPath expression as a whole, or the context node for each axis step considered individually? This question rarely arises with XPath 1.0 where it's quite hard to construct an expression that visits nodes in multiple documents (it can only be done using external variables, which are probably not supported in browser XPath implementations).

There's also a fundamental difference of philosophy: in the XPath specification we assume that the resolution of QNames can be done statically, during expression parsing, whereas this rule makes the resolution dependent on a dynamic property of the context node.

So I don't think we can reproduce the "willful violation" in our specs in precisely its WHATWG form.

What we can do is to recognise its good intent, namely to allow users doing simple things to not worry about namespaces.

My preferred way of achieving this intent is to allow a mode of processing, let's call it "default element namespace = any", where unprefixed names used as axis steps match by local name alone, ignoring namespace. This is useful in many other scenarios beyond HTML processing, and doesn't need a data model change.

**Comment by michaelhkay** [comment] 2023-11-02 00:12
This is a near duplicate of issue #296

**Comment by ndw** [comment] 2024-06-11 16:14
The CG agreed to close this issue without further action at [meeting 081](https://qt4cg.org/meeting/minutes/2024/06-11.html#close-without-action)

**Closed by ndw** 2024-06-11 16:14 UTC
Labels: XQFO, Enhancement, Propose Closing with No Action
