### ISSUE TITLE
fn:all, fn:some

### ISSUE THREAD

**Issue by benibela** [qt4cg/qtspecs#103] opened 2021-12-18 21:15 UTC
a) the text says the function returns boolean, but the signature says integer*

b) the text considers a case where the second argument is omitted, but there is no one argument function signature

c) `fn:some` is a wrapper around XQuery's `some` expression, and `fn:all` is a wrapper around XQuery's `every` expression. Is this not confusing and people would expect it to be a wrapper around some kind of `all` expression? Or be called `fn:every`?

d) I think it is pointless to have such functions when there are already the `some/every` XQuery expressions

**Comment by dnovatchev** [comment] 2021-12-21 02:02
> d) I think it is pointless to have such functions when there are already the `some/every` XQuery expressions

The world is not only XQuery. For people who maintain a functional programming approach to coding these two functions are really convenient and would significantly decrease their development time and proneness to errors.

Otherwise one could think that just having the 1 and 0 bits and the `and` gate is really sufficient to perform all classical (non-quantum) computations. While this is true, strictly speaking, people are constantly making progress in designing programming languages that are more and more appropriate for software development.

**Comment by rhdunn** [comment] 2021-12-21 08:36
See also https://github.com/qt4cg/qtspecs/issues/61.

**Comment by michaelhkay** [comment] 2022-08-09 09:24
Duplicate of #61

**Closed by michaelhkay** 2022-08-09 09:24 UTC
