### ISSUE TITLE
Namespaces for Functions

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#369] opened 2023-02-21 17:44 UTC
What problem are we trying to solve? Essentially, I think "namespace clutter".

Namespace clutter manifests itself in several different ways.

- Firstly, declaration clutter in source code. Here's the start of a module in an XSLT Stylesheet of medium complexity:

```
<xsl:stylesheet 
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
    xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    exclude-result-prefixes="#all"
    version="3.0" 
    xmlns="http://ns.saxonica.com/xslt/export" 
    xmlns:doc="http://www.saxonica.com/ns/documentation"
    xmlns:map="http://www.w3.org/2005/xpath-functions/map" 
    xmlns:ex="http://ns.saxonica.com/xslt/export" 
    xmlns:f="MyFunctions" 
    xmlns:t="MyTypes"
    expand-text="true">
```
Eight namespace declarations here, of which 3 are concerned with functions; and  Wit can get a lot worse than that.

- Secondly, namespace clutter in the static and dynamic context. The namespace bindings shown above don't disappear when the code is compiled; even with exclude-result-prefixes="yes", they have to hang around at run-time just in case someone tries to resolve a QName dynamically. Preserving the namespace context in the expression tree through optimization rewrites is a significant cost that has no user benefit; very rarely are they actually going to use the namespace context at run time.
- Thirdly, prefix clutter in the executable code. Writing `math:cos(math:cos($x))` is just so clumsy compared with `cos(cos($x))`.

I think there are a number of things we can do to reduce this.

First, separate out the namespace context for static resolution of function names as a separate part of the static context, used only for this purpose. Ensure that there is no functionality that depends on knowing this part of the static context at run time, so it can be discarded by the compiler as soon as function names are resolved. Then provide source syntax for binding function prefixes to function namespaces in XSLT and XQuery to populate this part of the static context; there is no reason this has to be done using XML namespace declarations. There is also no reason for having different bindings in force in different parts of a single module. And once we've separated these declarations from XML namespace declarations, there's no reason why we can't provide default bindings. We could also allow bindings to have cross-module scope to reduce duplicated code. Note: the xsl:function-library proposal in the current XSLT 4.0 draft tries to achieve some of these things.

Second, allow functions to be referenced by local name alone where the reference is unambiguous; and perhaps provide some aliasing mechanisms to make more existing names unambiguous.

We've explored a third idea, which is to introduce some kind of polymorphism where function names have local scope and are distinguished by the types of objects to which they are applied. I think that given our type system, this is very hard to achieve and I haven't seen any very satisfactory proposals. We also need to remember that there are considerable costs if we start resolving function names dynamically at run time. I wouldn't rule out making progress in this direction, but I'm not optimistic of coming up with a workable solution. There might be some simple things we could do, like having a single function `size()` that performs the work of both `map:size()` and `array:size()` depending on the argument.

**Comment by michaelhkay** [comment] 2023-02-22 08:07
I propose we do something along the following lines.

First, we define a new component in the static context, **function namespace bindings**, which is a mapping from prefixes to URIs. By default (for compatibility) it will be the same as **statically known namespaces**, but the key thing is that we allow it to be different. The function namespace bindings are used for resolving prefixes in function names when they appear in a static function call or function reference. Unlike the statically known namespaces, there is nothing in the language that requires the function namespace bindings to be accessible at run time; the processor can typically drop all knowledge of these namespace bindings as soon as an expression has been parsed.

Secondly, we replace the default function namespace (in the static context) with an **unprefixed function declaration list**. This is (conceptually) a list of all the function declarations that are eligible to be referenced using unprefixed names in in static function calls and function references. By default (for compatibility) it is a list of all the function declarations in the (old) default function namespace, but in principle it can be any list of function declarations, it is not required that they should all be in the same namespace. An unprefixed function reference is resolved by taking the first entry in the list that matches the required local name and arity: but see below for polymorphism.

Next step is to work out how to initialise these components in XQuery, XSLT, and XPath. Here's a sketch for XSLT:

- By default, for compatibility, the function namespace bindings are the same as the statically known namespaces, and the  unprefixed function declaration list is a list of all the function declarations in the **fn** namespace (XSLT 3.0 does not allow any other namespace to act as the default), followed by those in the **math** namespace (whose local names happen to be disjoint with the **fn** namespace).
- This can be overridden for any module by including an `xsl:import-functions` declaration in the module. 
- One form of this declaration, perhaps simply `<xsl:import-functions/>` with no parameters, should invoke a default set-up where a language-defined default set of bindings (for the standard namespaces fn, math, map, array, xs) and a standard list of unprefixed function declarations is established.
- The declaration should also allow explicit prefix=uri bindings to be set up. These bindings apply only to functions. The presence of the declaration means that conventionally-declared namespaces (using xmlns attributes) do not affect the function namespace bindings in the static context.
- The declaration should also allow an unprefixed function declaration list to be defined for the module. It should be possible to (a) add an entire namespace, (b) add an entire namespace with exceptions, (c) add specific functions.

**Polymorphism**

We could allow a limited capability for polymorphism by allowing the unprefixed function declaration list to contain two functions with the same name and arity range. A function call or reference that matches more than one function could then be resolved to a virtual function, where the body of the virtual function effectively contains a `typeswitch` that invokes one of the underlying "real" functions based on the actual type of the first supplied argument. This would allow the unprefixed function call `size()`, for example, to resolve to either map:size() or array:size() depending on the type of the first argument.

**Comment by dnovatchev** [comment] 2023-02-22 21:01
This sounds interesting.

Maybe we could have a look at how other PLs are doing similar things. For example, C# 10 **_[Global Using](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10#global-using-directives)_**

Also, we could even have a convention for a single file in a "project tree" or in the "project root" with name, let's say: "GlobalDispatches", from which the Processor takes all global information that allows it to resolve function namespacing. XSLT and XQuery stylesheets/modules could also import/include such a file. This means just one line per module/stylesheet that redirects to the same global file where all global dispatching information is stored for the whole project.

**Comment by michaelhkay** [comment] 2023-02-22 21:20
There's obviously a balance between making modules self contained, independent, and reusable (modular!) and avoiding repeated boilerplate. I did toy with a number of ideas for sharing these directives across modules but wasn't confident I had the right answer, and felt it was a distraction to the main ideas.

**Comment by rhdunn** [comment] 2023-05-02 15:51
MarkLogic has a `using namespace URILiteral;` declaration to bring the definitions of a given namespace into the current function/variable namespace content.

**Comment by dnovatchev** [comment] 2023-05-02 16:51
What about a new XSLT declaration (having global scope):

```xsl
 <xsl:register-prefix name="map" select="http://www.w3.org/2005/xpath-functions/map"/>
 <xsl:register-prefix name="array" select="http://www.w3.org/2005/xpath-functions/array"/>
 <xsl:register-prefix name="math" select="http://www.w3.org/2005/xpath-functions/math"/>
<!--   Etc.   -->
```

Enter all these just in one file and **xsl:import** it in all your stylesheet files with a single **_`<xsl:import>`_** declaration.

This eliminates the clutter.

It doesn't eliminate the need to use prefixes, but one could specify their own, preferred and shortest prefixes.

As @cmsmcq said, it is still not bad to use prefixes as the simplest and natural/non-confusing form of disambiguation.

**Comment by ndw** [comment] 2023-05-02 17:06
What are the scoping rules for such a set of imported declarations? Do they only apply to the module they're imported into, or do they apply to imported modules as well.

Stylesheets are XML documents and use XML mechanisms for managing namespaces. That means that a stylesheet (or other process) that constructs and XSLT stylesheet as an XML document can easily manage the in-scope namespaces. How will that apply if we allow defaulted namespace declarations?

**Comment by dnovatchev** [comment] 2023-05-02 18:47
> What are the scoping rules for such a set of imported declarations? Do they only apply to the module they're imported into, or do they apply to imported modules as well.

Even without any scoping rules:

Every stylesheet module (file) will contain a **_single_** **<xsl:import>**, like:

**`<xsl:import href="{someCommonUrlTo}global-prefix-registration.xsl"/>`**

Thus, if there are N prefixes and M stylesheet modules, this will require just a total N `<xsl:import>` (one in each stylesheet module), and not M*N namespace declarations as what we have at present.

If we have an XSLT application of moderate size, say 100 stylesheet modules and each at present requires 10 namespace declarations, using this mechanism will need 900 lines less code.

**Comment by dnovatchev** [comment] 2023-05-02 19:00
> Stylesheets are XML documents and use XML mechanisms for managing namespaces. That means that a stylesheet (or other process) that constructs and XSLT stylesheet as an XML document can easily manage the in-scope namespaces. How will that apply if we allow defaulted namespace declarations?

It will be the ultimate responsibility of the XSLT developer not to re-use the registered prefixes for any other purpose. Exactly as at present, redefining the "math:" perefix to some non-standard URI , and then attempting math:cos(0) will produce an error, and this is entirely caused by the developer  and generally is an accident.

**Comment by michaelhkay** [comment] 2023-05-02 21:17
I have spent some time after today's useful discussion trying to turn this into a concrete proposal, including changes needed, for example, to function declarations in XQuery and XSLT. The results, frankly, are disappointing. The problem essentially is that you can't remove complexity and retain backwards compatibility at the same time; any attempt to make the user's life easier ends up making the rules more complicated and difficult to understand and explain.

I'm not going to abandon all hope, but I think a series of proposals that are more modest in their ambition might be a better way forward. The discussion has crystallised that there are a number of rather separate problems that we are trying to solve.

**Comment by dnovatchev** [comment] 2023-05-02 22:12
> I have spent some time after today's useful discussion trying to turn this into a concrete proposal, including changes needed, for example, to function declarations in XQuery and XSLT. The results, frankly, are disappointing. The problem essentially is that you can't remove complexity and retain backwards compatibility at the same time; any attempt to make the user's life easier ends up making the rules more complicated and difficult to understand and explain.
> 
> I'm not going to abandon all hope, but I think a series of proposals that are more modest in their ambition might be a better way forward. The discussion has crystallised that there are a number of rather separate problems that we are trying to solve.

@michaelhkay What specific problems could you bring forward with the proposal for having an **<xsl:register-prefix>** declaration and having all these at a central stylesheet module of an XSLT application?

**Comment by michaelhkay** [comment] 2023-05-04 11:28
I am submitting a PR that addresses a subset of the problems identified. This proposal is confined to XSLT only. It proposes a new attribute `fixed-prefixes` on the `xsl:stylesheet` element; its value is a list of prefixes.

It can be used to add "known" conventional prefixes to the static context for all XPath expressions in the module simply by doing, for example `fixed-prefixes="math map array"`.

It can also be used to force inheritance of namespace bindings through the include-import tree: if an including stylesheet declares a binding `xmlns:local="http://my-functions/"` then the imported stylesheet can declare this namespace by doing `fixed-prefixes="local"`.

If the `fixed-prefixes` attribute is present, then all expressions in the stylesheet have the same set of static namespaces in the static (and dynamic) context; it is not affected by namespace declarations on (for example) literal result elements. This is designed to reduce the overhead in maintaining fine-grained namespace context for every expression in the stylesheet (which can be considerable, for example when inlining a function from a different module).

I did experiment with top-level declarations along the lines of @dnovatchev's `xsl:register-prefix`. The main problem was defining their scope, especially their impact on static expressions (such as `use-when`). If they only affect XPath expressions appearing after the declaration, then you lose the benefits of having a uniform static context throughout the module, but if you allow forwards references, then you can't process `use-when` in your initial pass through the data.

I have dropped the incompletely specified `xsl:function-library` appearing in the current draft.

**Comment by dnovatchev** [comment] 2023-05-04 15:11
> I did experiment with top-level declarations along the lines of @dnovatchev's `xsl:register-prefix`. The main problem was defining their scope, especially their impact on static expressions (such as `use-when`). If they only affect XPath expressions appearing after the declaration, then you lose the benefits of having a uniform static context throughout the module, but if you allow forwards references, then you can't process `use-when` in your initial pass through the data.

I am not sure what is the problem. 😞 

Could you, please, elaborate on this?

**Comment by michaelhkay** [comment] 2023-05-04 15:50
>I am not sure what is the problem. Could you, please, elaborate on this?

I'll try. I tried to specify this in a number of ways, and they all hit different problems. It basically depends on what rules you try to impose about (a) the position of the declaration within the stylesheet module, and (b) the rules for consistency with other namespace declarations.

Firstly, the position of the declaration. If we allowed it to appear anywhere, then to enable processing of static expressions like use-when to be done on-the-fly without lookahead, we would have to say that it only affects things that appear after the declaration in stylesheet order. But that would mean that different parts of the stylesheet have different in-scope namespaces, which is one of the things I wanted to avoid -- having to retain fine-grained namespace context when you do rewrites such as function inlining is complex and expensive. So another option is to require it to appear before anything else in the module. But even that isn't ideal because it's possible to have attributes with prefixes (for example default-mode) on the xsl:stylesheet element itself, which is necessarily before the first declaration in the stylesheet. That's why I decided to go for an attribute on xsl:stylesheet rather than a declaration. I did consider having something like an `import-namespaces` attribute on `xsl:stylesheet`, which I think would be viable, but I felt it was more complex than what I ended up proposing.

Secondly, the consistency rules. Are you allowed two register-prefix declarations and what happens if they conflict with each other? Do they both take effect, applying to different regions of the stylesheet module? What happens if there's a conflict between the imported namespace bindings and (a) the namespace declarations on the xsl:stylesheet element, or (b) namespace bindings on other elements appearing later in the stylesheet? I went down the path of trying to define all these consistency rules, then stopped in my tracks and thought, this is increasing complexity when our aim is to reduce it.

**Comment by dnovatchev** [comment] 2023-05-04 17:17
> I'll try. I tried to specify this in a number of ways, and they all hit different problems. It basically depends on what rules you try to impose about (a) the position of the declaration within the stylesheet module, and (b) the rules for consistency with other namespace declarations.

I think all these problems are eliminated if we decide not to have such declarations at all residing in any stylesheet module of the XSLT application.

Instead, we could have all these in a single, centrally located and uniquely identified (having a specific, predefined name, (such as **_global-prefixes.xsl_**),  resource (say, having the same path (or residing in the same directory in a filesystem-world)) as the primary stylesheet module.

The rule is that the first thing the XSLT processor does, even before starting to read any of the stylesheet modules, is to find this **_global-prefixes_** resource and ingest the global prefixes defined by it.

I think that this solution avoids any of the two cited problems.

The location of the **_global-prefixes_** may be even specified in an environment variable on the XSLT-processor execution machine.

An error will be signaled for any redefinition of any of the global prefixes within the code. Redefinition is binding a global prefix to a string (namespace-uri) **different** from its globally-provided value. Thus, in legacy code there could still be namespace declarations that happen to bind the global prefix to the **same** namespace-uri that is its globally specified value, and this is not an error.

This rule supports backwards compatibility for any legacy code-base that declares the standard namespace prefix bindings.

How does this sound?

**Comment by michaelhkay** [comment] 2023-05-05 07:19
I'm not in favour of using a predefined name (it makes life difficult for an application that is using many different stylesheets to process different kinds of source document, and it doesn't fit well with web architecture. And "environment variables" aren't a good fit to web architecture either. Also, I don't think we should impose that every stylesheeet module should use a global namespace document; it makes reuse of modules more difficult.

It would be possible, I think, to replace the fixed-prefixes attribute in my proposal with a `fixed-namespaces="uri"` attribute (or similar) on the `xsl:stylesheet` element, so any module could, at its choice, get the namespace bindings from some external, perhaps central source.

One thing I would worry about is that this would encourage people to use a "universal namespace document" that declares every prefix known to mankind. That's something we don't want to encourage; namespace proliferation adds overheads that are probably higher than most users realise. One advantage of my proposal is that you have to "opt in" to state the namespaces you want at module level.

It would also of course be possible to combine the two ideas. But that's feature-creep, and we want to keep things as simple as we possibly can.

**Comment by dnovatchev** [comment] 2023-05-05 16:29
> It would be possible, I think, to replace the fixed-prefixes attribute in my proposal with a `fixed-namespaces="uri"` attribute (or similar) on the `xsl:stylesheet` element, so any module could, at its choice, get the namespace bindings from some external, perhaps central source.

👍
 
> 
> One thing I would worry about is that this would encourage people to use a "universal namespace document" that declares every prefix known to mankind. That's something we don't want to encourage; namespace proliferation adds overheads that are probably higher than most users realise. One advantage of my proposal is that you have to "opt in" to state the namespaces you want at module level.

**We can avoid this with a simple rule**: If no such `fixed-namespaces="uri"` attribute is specified, the default, **minimum** set of fixed bindings will be used: for the prefixes "map:", "array:". "math:", "xs:", "err:" and maybe "ser:", and these will be bound, respectively, to the corresponding standard namespace-uris as specified in the **_[Spec](https://www.w3.org/TR/xpath-functions-31/#namespace-prefixes)_**.

Thus in most cases the users will not need to create even a single such resource, and they would not even need to add this new attribute on the `xsl:stylesheet` element in any module.

> 
> Another concern is that (unlike my proposal) the facility would add no value for single-module stylesheets (it adds complexity without any obvious benefits) and as a result people wouldn't get into the habit of using it when they come to write something more complex; it's a feature that could easily sit on the shelf unused.

With the above rule this concern is completely avoided, isn't it?

> 
> It would also of course be possible to combine the two ideas. But that's feature-creep, and we want to keep things as simple as we possibly can.

With the above rule, as already pointed out, in most cases the users will not need to write a single additional character to specify the fixed prefixes bindings, so what "feature-creep" are we talking about?

**Comment by michaelhkay** [comment] 2023-10-18 21:17
See also issue #757

**Comment by ndw** [comment] 2024-05-14 16:08
The CG agreed to close this issue without further action at [meeting 077](https://qt4cg.org/meeting/minutes/2024/05-14.html).

**Closed by ndw** 2024-05-14 16:08 UTC
Labels: XPath, XQuery, XSLT, Enhancement, Propose Closing with No Action
