### ISSUE TITLE
fn:parts() - extract the parts of a (not-really) atomic value

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#463] opened 2023-04-28 20:09 UTC
We have a whole raft of functions to extract the parts of date, time, and duration values: month-from-dateTime(), etc etc.

These aren't particularly convenient to use, for example getting multiple components of a duration is clumsy; and there are gaps, for example there are no functions to extract the parts of a `gMonthDay`.

I propose a general-purpose function `fn:parts()` which turns any of these composite atomic values into a map, enabling you to replace a call on `get-month-from-dateTime($value)` with `parts($value)?month`.

So far this dupllicates existing functionality perhaps with a bit of added convenience. However, the mechanism is much more extensible and flexible than what we have now:

* we can apply it to atomic types that currently have no decomposition operators, such as gMonthDay
* we can easily add additional components such as `day-of-week` or `quarter` or `day-of-year` or `julian-day` that are currently not available, or only available clumsily using format-dateTime().
* the parts() function is polymorphic, so the same code can be used to get the year (say) from a date, a dateTime, or a gYearMonth.

**Comment by ndw** [comment] 2023-04-29 06:58
👍 with the comment that `fn:parts` seems like an awfully generic name. I suppose the problem is that it applies to a whole bunch of types not all of which are dates, times, or dateTimes. Would it also apply to durations?

**Comment by ChristianGruen** [comment] 2023-04-29 07:38
If we wanted to add components such as `julian-day`, it may be confusing to call such a value the »part of a date« (but again I'm no native speaker). If I get such a result, I would rather assume that the argument was analyzed to be able to provide single properties of it.

Maybe `fn:analyze` could be an alternative, analogous to `fn:analyze-string`, but as a more general feature for all kinds of items?

As the date/duration is not mentioned in the function name, I believe we should go a step further and extend it to other types: We could return the prefix/local name/uri/eqname-representation of QNames, the integer/fractional part and sign of numbers, the length of strings, … The function would be easy to explore, you could simply call it with an item and see what it returns, without digesting the documentation.

Or we use `fn:parse`, analogous to the new `fn:parse-uri` function (but I was already wondering whether `fn:analyze-uri` wouldn't be a better name, as the function doesn't deliver the denoted target, opposed to `fn:parse-integer`, `fn:parse-xml` or `fn:parse-QName`, but rather splits it up into… parts or components. Sorry, different topic, and a bit late).

**Comment by ChristianGruen** [comment] 2023-04-29 08:51
Suggestions

Type | Parts, components, properties (xs:integer, unless specified)
--- | ---
`xs:duration` | `years`<br>`months`<br>`days`<br>`hours`<br>`minutes`<br>`seconds`
`xs:dateTime` | `year`<br>`month`, `day`<br>`hours`<br>`minutes`<br>`seconds`<br>`timezone` (xs:string)
`xs:date` | `year`<br>`month`<br>`day`
`xs:time` | `hours`<br>`minutes`<br>`seconds`<br>`timezone` (xs:string)
`xs:gYearMonth` | `year`<br>`month`
`xs:gYear` | `year`
`xs:gMonthDay` | `month`<br>`day`
`xs:gMonth` | `month`
`xs:gDay` | `day`
`xs:QName` | `prefix` (xs:string)<br>`local-name` (xs:string)<br>`namespace-uri` (xs:string)
`xs:double` | `NaN` (xs:boolean)<br>`INF` (xs:boolean)<br>`positive` (xs:boolean?)<br>`integer-part` (xs:double?)<br>`fractional-part` (xs:double?)
`xs:float` | `NaN` (xs:boolean)<br>`INF` (xs:boolean)<br>`positive` (xs:boolean?)<br>`integer-part` (xs:float?)<br>`fractional-part` (xs:float?)
`xs:decimal` | `positive` (xs:boolean?)<br>`integer-part` (xs:decimal)<br>`fractional-part` (xs:decimal)
`xs:integer` | `positive` (xs:boolean?)
`xs:string` | `length`<br>possibly: `characters` (xs:string*)
`xs:binary` (see #130) | `length`<br>possibly: `octets` (xs:integer*)
`xs:anyURI` | ...how should it relate to `fn:parse-uri` ?

Thinking of `fn:build-uri`, one might immediately expect a `fn:build` function…

**Comment by dnovatchev** [comment] 2023-04-29 19:37
I think that these might be better names (just the first that come into mind):

 - **_fn:fragments_**
 - **_fn:breakdown_**
- **_fn:decomposition_**
- **_fn:constituents_**

**Comment by ndw** [comment] 2023-04-30 08:06
If we're going to expand it to cover all of the types @ChristianGruen outlined (and any more that are proposed), then I like the "constituents" proposal by @dnovatchev , though I'd probably go for `fn:constituent-parts` myself, for clarity. Idiomatically, "the constituent parts" of something rings more naturally to my ears than "the constituents" of something.

Alternatively, I suppose we could create a family of functions rather than a single function: `fn:dateTime-parts`, `fn:duration-parts`, `fn:number-parts`, `fn:qname-parts`, etc. If we went that way, I'd be inclined to rename `fn:parse-uri` to `fn:uri-parts` and align its semantics as necessary. And then we'd have to justify why there aren't builders for all of them (or remove `fn:build-uri` so that there are builders for none of them, I suppose).

It's obviously useful, obviously easy to implement, and probably one of a thousand such examples. Really makes me wonder if we'd be wise to try to solve the library problem a la maven, nuget, chocolat, etc. for XPath/XQuery/XSLT so that this could be implemented outside of the specification and simply used by everyone.

**Comment by dnovatchev** [comment] 2023-04-30 17:18
> I think that these might be better names (just the first that come into mind):
> 
> * **_fn:fragments_**
> * **_fn:breakdown_**
> * **_fn:units_**
> * **_fn:details_**
> * **_fn:subparts_**
> * **_fn:properties_**
> * **_fn:constituents_**
> * **_fn:drilldown_**
> * **_fn:decomposition_**

Looking at all of these, my preferred one is **_fn:properties_**

It is a fact that the value of a specific  "part" can be regarded as the value of a corresponding property.

Thus we can write:

  **properties($dateTime)?month**

or 

  **$dateTime => properties()?month**

or maybe even

  **$dateTime?month** 

assuming that every value has its **property-value map**, and can be implicitly cast to that map, if this value isn't itself a map.

Another advantage is that the XPath processor can associate to every **value** (of any type, or most generally `item()*`) a set of **standard properties**, such as _type_, _type-name_, _guid_, _ancestor-paths_ (for values that are buried deep into maps or arrays), etc.

If this reminds us of Python or Javascript,  maybe this is not totally coincidental. At least we know that such approach has been successful in more than one other language, and also know in advance what to expect, based on what plusses and minuses were reported by their users.

**Comment by michaelhkay** [comment] 2023-04-30 18:23
I agree, fn:properties() would be a better name.

>We could provide an option for requesting properties that may consume a lot of memory

I thought of providing some of these properties as methods, e.g.  `properties($dateTime)?julian-day()` but decided that if the implementation wants to compute some properties lazily on demand, it's free to do so, it doesn't need a different syntax.

**Comment by ChristianGruen** [comment] 2023-05-02 09:50
+1 for `fn:properties`. Do we want to consider other types beside dates, times and durations?

**Comment by michaelhkay** [comment] 2023-05-02 11:06
>Do we want to consider other types beside dates, times and durations?

Yes definitely. I'm less sure though whether we should extend it to items other than atomic values.

**Comment by michaelhkay** [comment] 2024-03-12 21:05
Can't find the energy to specify this, and I think we need to stop adding "nice-to-have" functions that we can live without. So I proposed to close with no action.

**Comment by ndw** [comment] 2024-03-19 17:32
The CG agreed to close this issue without further action at [meeting 070](https://qt4cg.org/meeting/minutes/2024/03-19.html#close-without-action).

**Closed by ndw** 2024-03-19 17:32 UTC
Labels: XQFO, Feature, Propose Closing with No Action
