### ISSUE TITLE
Defining a common function library for XPath, XSLT, and XQuery applications

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qtspecs#652] opened 2023-08-07 17:04 UTC
This issue is motivated by Mary Holstege's talk at Balisage 2023: Adventures in Single-Sourcing XSLT and XQuery

https://www.balisage.net/Proceedings/vol28/html/Holstege01/BalisageVol28-Holstege01.html

It is also motivated by other issues that have been raised here proposing improved capabilities for writing applications in pure XPath.

I propose that we define a syntax for creating a module containing a set of function definitions that can be used to define a function library available to both XQuery and XSLT applications, and potentially also by pure XPath applications. A file should contain all the functions in one namespace. The format should be suitable for translation into other formats such as XSLT and XQuery, which means it should be in XML (though we could also consider JSON). We should provide XSLT stylesheets that convert libraries in this format into XSLT stylesheet modules or XQuery library modules.

Function signatures should be expressed in an XML syntax similar to `xsl:function` in XSLT.

Function bodies should generally be written in the form of a single XPath expression, though there should be fallback mechanisms to allow XSLT and XQuery implementations to be supplied in cases where XPath lacks sufficient expressive power.

There should be mechanisms to define the more important components of the static context, such as namespace bindings and dependencies on other function libraries.

We could consider using this format to publish "polyfill" implementations of many of the new XPath 4.0 functions.

**Comment by dnovatchev** [comment] 2023-08-13 01:31
> Function signatures should be expressed in an XML syntax similar to xsl:function in XSLT.

>The format should be suitable for translation into other formats such as XSLT and XQuery, which means it should be in XML (though we could also consider JSON). We should provide XSLT stylesheets that convert libraries in this format into XSLT stylesheet modules or XQuery library modules.

Reminds me of **[XQueryX](https://www.w3.org/TR/xqueryx-31/)**.

As far as I am aware, close to nobody is using it.

Why pore so much effort as proposed, only in order to ask to the users to write complex and unreadable XML documents that rather well obfuscate the genuine, original code?

Since several years I have implemented and used a single, common set of XPath function libraries named **FunXPath**, in which a function library contains **only true XPath code with no obfuscation**. As intended these are loaded and used both with XSLT and XQuery, and can be loaded and used from any standalone XPath program.

Before investing considerable effort in fancy (complex) syntax for specifying function libraries, I recommend that the design of the already implemented and used, genuine XPath-code function library **FunXPath** be considered as an already proven and simple way to provide the desired function-library mechanism for all XPath / XSLT and XQuery users.

It is implemented completely in XPath 3.1 (using two "extension functions" for the (XSLT and XQuery) loaders written, correspondingly in XSLT (shown above) and XQuery).

Here is an example - the function library **general.xpath**:

```xq
let $id := function($arg as item()*) as item()*
{ $arg},

  $flip := function($f as function(item()*,item()*) as item()*) as function(item()*, item()*) as item()*
  {
    function($y as item()*, $x as item()*) {$f($x, $y)}
  },
  
  $compose := function($f as function(item()*) as item()*, $g as function(item()*) as item()*) as function(item()*) as item()*
  {
    function($x as item()*)
    {
      $f($g($x))
    }
    
  }

  return
    map {
      'id'      : $id,
      'flip'    : $flip,
      'compose' : $compose
    }
```

And testing it with XSLTL

```xsl
<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:array="http://www.w3.org/2005/xpath-functions/array"
  xmlns:f="http://www.fxpath.org">
  <xsl:import href="../initialization/Loader.xsl"/>
  
  <xsl:output method="text" omit-xml-declaration="yes" indent="yes"/>
  
  <!-- ======= Load the file with the XPath functions to be tested ================== -->
  <xsl:variable name="vBaseFXpathUri" 
    select="(environment-variable('FXpathDir')[normalize-space()], '..')[1]"/>
 
  <xsl:variable name="vGen" as="map(*)"
    select="f:loadFunctionLibraries($vBaseFXpathUri || '/f/general.xpath')"/>
  
  <!-- ======== Load the Ops Xpath Function Library ================================ -->
    <xsl:variable name="vOps" as="map(*)"
    select="f:loadFunctionLibraries($vBaseFXpathUri || '/f/operators.xpath')"/>

  
  <xsl:template name="xsl:initial-template">
    <xsl:sequence select="$vGen?flip($vOps?div) (3, 6)"/>

  </xsl:template>
</xsl:stylesheet>
```

Running this with Saxon (under Oxygen) produces the wanted result:

**2**

---

And the XSLT and XQuery loaders are pretty simple, straightforward and understandable.

Here is the XSLT loader:

```xsl
xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  xmlns:map="http://www.w3.org/2005/xpath-functions/map"
  xmlns:f="http://www.fxpath.org">
    
  <xsl:variable name="vBaseFXpathUri" 
    select="(environment-variable('FXpathDir')[normalize-space()], '..')[1]"/>
  
  <xsl:template name="loadFunctionLibraries" as="map(*)">
    <xsl:param name="pFilePaths" as="xs:string+"/>
      <xsl:sequence select="f:loadFunctionLibraries($pFilePaths)"/>
  </xsl:template>
    
  
  <xsl:function name="f:loadFunctionLibraries" as="map(*)" visibility="public">
    <xsl:param name="pLibrariesUris" as="xs:string+"/>
    
    <xsl:variable name="vAllText" as="xs:string+" select=
      "string-join(
                  (for $p in $pLibrariesUris
                    return unparsed-text($p)
                  ),
                  ',&#xA;'
                 )"/>
    
    <xsl:evaluate xpath="'map:merge((' || $vAllText || '))'">
      <xsl:with-param name="pBaseFXpathUri" select="$vBaseFXpathUri"/>
    </xsl:evaluate>
  </xsl:function>
</xsl:stylesheet>
```

Here is an example of a bigger XPath library, that internally loads and uses two other XPath libraires:

```xq
(: =============== Include operators.xpath ============================:)
let $ops := Q{http://www.fxpath.org}loadFunctionLibraries#1(
concat($pBaseFXpathUri, '/f/operators.xpath')),
                                                            
(: ================ Include folds.xpath ===============================:)
  $folds := Q{http://www.fxpath.org}loadFunctionLibraries#1(
concat($pBaseFXpathUri, '/f/folds.xpath')
                                                            ), 

 (:    Special Folds
   ====================================================================:)
   $and := function ($booleans as xs:boolean*) as xs:boolean
{
  $folds?foldl_($ops?conjunction, true(), $booleans)
}, 

   $or := function ($booleans as xs:boolean*) as xs:boolean
{
  $folds?foldl_($ops?disjunction, false(), $booleans)
},

   $any := function($f as function(item()) as xs:boolean, $list as item()* ) as xs:boolean
{
  $or($list!$f(.))
},   

   $all := function($f as function(item()) as xs:boolean, $list as item()* ) as xs:boolean
{
  $and($list!$f(.))
},

  $sum := function ($nums as xs:numeric*) as xs:numeric
{
  $folds?foldl_($ops?add, 0, $nums)
},

  $product := function ($nums as xs:numeric*) as xs:numeric
{
  $folds?foldl_($ops?mult, 1, $nums)
},

  $minimum := function ($orderedItems as item()*) as item()
{
 $folds?foldl_(function($a, $b){if($a le $b) then $a else $b}, $orderedItems[last()], $orderedItems)
},

  $maximum := function ($orderedItems as item()*) as item()
{
 $folds?foldl_(function($a, $b){if($a ge $b) then $a else $b}, $orderedItems[last()], $orderedItems)
},

  $concat := function ($strings as xs:string*) as xs:string
{
 $folds?foldr_($ops?concatenation, '', $strings)
}

   return
      map { 
            'and'     : $and,
            'or'      : $or,
            'any'     : $any,
            'all'     : $all,
            'sum'     : $sum,
            'product' : $product,
            'minimum' : $minimum,
            'maximum' : $maximum,
            'concat'  : $concat
            }
```

And its tests written in XSLT:

```xsl
<xsl:stylesheet version="3.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:f="http://www.fxpath.org">
  <xsl:import href="../initialization/Loader.xsl"/>
  
  <xsl:output method="text" omit-xml-declaration="yes" indent="yes"/>
  
 <!-- ======= Load the file with the XPath functions to be tested ================== -->
  <xsl:variable name="vBaseFXpathUri" 
    select="(environment-variable('FXpathDir')[normalize-space()], '..')[1]"/>
  
  <xsl:variable name="vFuns" as="map(*)" 
    select="f:loadFunctionLibraries($vBaseFXpathUri || '/f/special-folds.xpath')"/>
  <!-- ============================================================================== -->
  <xsl:variable name="NL" select="'&#xA;'"/>
  
  <xsl:template name="xsl:initial-template">
    <xsl:sequence select="$vFuns?and((true(), true(), true())), $NL"/>
    <xsl:sequence select="$vFuns?and((true(), true(), false())), $NL"/>
    
    <xsl:sequence select="$vFuns?or((false(), false(), false())), $NL"/>
    <xsl:sequence select="$vFuns?or((true(), false(), false())), $NL"/>
    
      <xsl:sequence select="$vFuns?any(function($n) {$n idiv 2 * 2 eq $n}, (1,3,5)), $NL"/>
      <xsl:sequence select="$vFuns?any(function($n) {$n idiv 2 * 2 eq $n}, (1,3,6)), $NL"/>
    
      <xsl:sequence select="$vFuns?all(function($n) {$n idiv 2 * 2 eq $n}, (1,2,6)), $NL"/>
      <xsl:sequence select="$vFuns?all(function($n) {$n idiv 2 * 2 eq $n}, (0,2,6)), $NL"/>
    
      <xsl:sequence select="$vFuns?sum(1 to 10), $NL"/>
      <xsl:sequence select="$vFuns?product(1 to 6), $NL"/>
    
      <xsl:sequence select="$vFuns?minimum((6,8,3, -2)), $NL"/>
      <xsl:sequence select="$vFuns?minimum(('Alas', 'Baba', 'A2', 'Zebra')), $NL"/>
      <xsl:sequence select="$vFuns?minimum((xs:date('2001-07-14'), current-date())), $NL"/>
    
      <xsl:sequence select="$vFuns?maximum((6,8,3, -2)), $NL"/>
      <xsl:sequence select="$vFuns?maximum(('Alas', 'Baba', 'A2', 'Zebra')), $NL"/>
      <xsl:sequence select="$vFuns?maximum((xs:date('2001-07-14'), current-date())), $NL"/>
    
      <xsl:sequence select="$vFuns?concat(('a1', 'b2', 'c3')), $NL"/>
  </xsl:template>
</xsl:stylesheet>
```

And again, running the above tests produces the wanted, correct results:

```
true 
 false 
 false 
 true 
 false 
 true 
 false 
 true 
 55 
 720 
 -2 
 A2 
 2001-07-14 
 8 
 Zebra 
 2023-08-12-07:00 
 a1b2c3 
```

**Comment by michaelhkay** [comment] 2023-08-13 06:29
The proposal differs from XQueryX in that the body of a function is written in pure human-readable XPath. XQueryX was never intended to be human-readable or writable.

It differs from FunXPath in that:

 (a) there is no difficulty writing functions that are recursive (or mutually recursive), and 

 (b) functions can be called statically rather than dynamically, which potentialy gives better type-checking, optimisation, and diagnostics.

It also provides a vehicle for declaring aspects of the static context for the functions, such as namespaces and collations.

Michael Kay
Saxonica

**Comment by dnovatchev** [comment] 2023-08-13 16:35
> The proposal differs from XQueryX in that the body of a function is written in pure human-readable XPath. XQueryX was never intended to be human-readable or writable. It differs from FunXPath in that: 

> (a) there is no difficulty writing functions that are recursive (or mutually recursive), and 

**There is no "difficulty" in implementing recursion in XPath**, as shown more than 10 years ago. This was provided as a blog article, Balisage 2013 paper and as a significant part of a Pluralsight course, that has been watched by more than 4000 people.
And most people I know have shared that this concept is easy to understand and use in practice.

> (b) functions can be called statically rather than dynamically, which **_potentially_** gives better type-checking, optimization, and diagnostics. 

Potentially?

> It also provides a vehicle for declaring aspects of the static context for the functions, such as namespaces and collations. 

Not exactly true. Reading the XSLT 3.0 specification for **<xsl:evaluate>** and **[the description of the static context used in <xsl:evaluate>](https://www.w3.org/TR/xslt-30/#evaluate-static-context)** we see that:

1. All statically known namespaces are provided with a node that is the value of evaluating the _`namespace-context`_ attribute. To quote the spec: 
"_the in-scope namespaces of the resulting node are used as the statically known namespaces for the target expression. The binding for the default namespace in the in-scope namespaces is used as the default namespace for elements and types in the target expression_."

2, The same official specification (a bullet below)  also defines how statically-known collations are provided:

" 
• Statically known collations: the same as the collations available at this point in the stylesheet.

• Default collation: the same as the default collation defined at this point in the stylesheet (for example, by use of the [xsl:]default-collation attribute)
"

It is  also possible in FunXPath to use **[`fn:load-xquery-module`](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#func-load-xquery-module)** in a loader that doesn't depend on **[`fn:transform`](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#func-transform)** . 

Again, calling **fn:load-xquery-module** allows to pass such data as:

- context-item
- external variables (whose values may be functions)
- location -hints
etc. ...

---

And you haven't addressed **the most weak part of this proposal - it creates redundancy**!

 1. With every change in the function library the user must run the transformations to produce the XQuery and XSLT modules.
 
 2. The user may forget to run these transformations for either XSLT or XQuery (in which case the XSLT code and the XQuery code will be inconsistent with each other!) or both (in which case the user's code will be obsolete.
 
 3.  If we have N other hosts of XPath (different from XSLT and XQuery), a user might have to run N such transformations. Also, the degree of redundancy increases dramatically

I think such redundancy and increased expectations about the user involvement in translating the XPath functions, defeats the purpose of the proposal.

**Comment by ChristianGruen** [comment] 2023-08-13 17:03
I wonder whether XQuery users would need such a feature, as the existing module import works fine. But I see that users could possibly benefit from the availability of modules that have been written by XPath/XSLT developers.

I'm not so thrilled that this feature, if properly implemented, would require a processor that's able to parse pure XPath. We've never supported that as there was no need for it. The EXPath packaging mechanism is more flexible in this regard. 

Do we know if there is any implementation apart from Saxon that supports both XPath  and XQuery 3.1 independently? If not, chances could be high that this feature will only be supported by a single processor.

**Comment by ChristianGruen** [comment] 2023-08-13 17:11
@dnovatchev I know that many people used FunctX (I usually don’t), but I can't find a single reference to the FunXPath code you mentioned. I assume it's private or commercial? If no, where can we find it, and how can this library be embedded/imported in existing XQuery/XSLT projects? Does it work with all implementations, or does it contain vendor-specific code?

**Comment by dnovatchev** [comment] 2023-08-13 17:17
> @dnovatchev I know that many people use FunctX (I usually don’t), but I can't find a single reference to the FunXPath code you mentioned. I assume it's private or commercial? If no, where can we find it, and how can this library be embedded/imported in existing XQuery/XSLT projects? Does it work with all implementations, or does it contain vendor-specific code?

@ChristianGruen Very good question, thank you.

I am guilty of having not made FunXPath public yet, because I wanted to add more and more functions / data-types to it, and we know well that such perfectionism is not good.

I need to make some cleanup of the library and will post a blog article and make FunXPath accessible to everyone.

I will immediately give you access (be warned that the core content hasn't been touched for several years) and will appreciate discussing this and your opinion about the contents of the library.

Thanks again!

**Comment by ChristianGruen** [comment] 2023-08-13 17:27
@michaelhkay I’m actually not sure if I understood correctly what this issue is about. The title is:

> Defining a common function library for XPath, XSLT, and XQuery applications

Do we really want to define a joint library, or isn’t this about a mechanism/syntax/feature/… to convert input (preferably XML) to a set of executable functions?

**Comment by michaelhkay** [comment] 2023-08-13 19:21
This is about providing a mechanism for use by people who (like Mary) want to define a function library that can be used both in XSLT and in XQuery applications, either using the same processor or different processors.

I imagine that we would provide stylesheets that convert this format to standard XQuery and XSLT syntax, so there is no need for native support in individual XSLT and XQuery processors.

**Comment by ChristianGruen** [comment] 2023-08-13 19:40
> I imagine that we would provide stylesheets that convert this format to standard XQuery and XSLT syntax, so there is no need for native support in individual XSLT and XQuery processors.

Thanks. Sounds like a good choice.

**Comment by dnovatchev** [comment] 2023-08-13 22:11
> I imagine that we would provide stylesheets that convert this format to standard XQuery and XSLT syntax, so there is no need for native support in individual XSLT and XQuery processors.

As said earlier, both XQuery and XSLT work with pure XPath expressions, thus there is no need to "_**provide stylesheets that convert this format to standard XQuery and XSLT syntax**_".

Moreover, this brings additional and unnecessary load on the user, including new learning requirements, brings redundancy and error-proneness, and unnecessarily increases the carbon footprint of using the X* languages and any language processor that can host XPath.

Putting it simply: We can happily have pure XPath function libraries without having to convert these "**_to standard XQuery and XSLT syntax_**" and live in a cleaner environment.

**Comment by michaelhkay** [comment] 2023-08-13 22:36
"additional and unnecessary load on the user" - the entire justification for this proposal is based on the burden currently faced by a particular user, Mary Holstege, as described in her Balisage paper cited above, meeting what ought to be quite a simple requirement.

**Comment by dnovatchev** [comment] 2023-08-13 23:00
> "additional and unnecessary load on the user" - the entire justification for this proposal is based on the burden currently faced by a particular user, Mary Holstege, as described in her Balisage paper cited above, meeting what ought to be quite a simple requirement.

Yes, and she was not aware that something very simple, that doesn't require such translations was available.

She could have simply called [**`fn:load-xquery-module`**](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#func-load-xquery-module)

**Comment by michaelhkay** [comment] 2024-05-14 22:39
No consensus emerged on this discussion so I propose closing it.

**Comment by ndw** [comment] 2024-05-21 16:07
The CG agreed to close this issue without further action at [meeting 078](https://qt4cg.org/meeting/minutes/2024/05-21.html).

**Closed by ndw** 2024-05-21 16:07 UTC
Labels: XPath, XQuery, XSLT, Feature, Propose Closing with No Action
