### ISSUE TITLE
Incorrect statement about named modes

### ISSUE THREAD

**Issue by maxtoroq** [qt4cg/qtspecs#270] opened 2022-11-24 13:56 UTC
On the description of the 'visibility' attribute [here](https://qt4cg.org/specifications/xslt-40/Overview-diff.html#declaring-modes) it says:

> A named mode is not eligible to be used as the [initial mode](https://qt4cg.org/specifications/xslt-40/Overview-diff.html#dt-initial-mode) if its visibility is private.

But, if the mode is designated as default mode of the implicit or explicit `xsl:package` then it's eligible as an initial mode. Having a private visibility does not affect it's initial status. Furthermore, the unnamed mode is always private, and always initial.

**Comment by michaelhkay** [comment] 2022-11-24 16:56
This is a duplicate of https://www.w3.org/Bugs/Public/show_bug.cgi?id=30405 -- though that's not very useful to know since the issue was never resolved.

**Comment by michaelhkay** [comment] 2022-11-24 17:01
For what it's worth, I think Saxon implements the rule as written: a named mode declared implicitly or explicitly as private is eligible as the initial mode if and only if it is also declared as the default mode.

**Comment by maxtoroq** [comment] 2022-11-24 20:32
I did test with Saxon and the results confirmed my interpretation of the spec.

**Closed** 2022-11-30 10:57 UTC
Labels: Bug, XSLT
